half_precision: False
device: cuda

architecture:
  name: Mask-RCNN
  box_detections_per_img: 540
  num_classes: 3

data:
  sample_submission: sample_submission.csv
  train_json: annotations_train_4X.json
  val_json: annotations_val_4X.json
  data_path: data/
  mask_threshold:
    1: 0.55
    2: 0.75
    3: 0.6
  min_score:
    1: 0.55
    2: 0.75
    3: 0.5

model:
  exp_name: exp_6_4X
  save_path: experiments

training:
  epochs: 100
  save_step: 5
  shuffle: true
  num_workers: 8
  batch_size: 15
  autoresume: true

optimizer:
  type: SGD
  lr: !!float 1e-4
  weight_decay: !!float 5e-4
  momentum: 0.9
  scheduler: false
