half_precision: False
device: cuda

architecture:
  name: Mask-RCNN
  box_detections_per_img: 540
  num_classes: 3

data:
  sample_submission: sample_submission.csv
  train_json: annotations_train_4X.json
  val_json: annotations_val_4X.json
  data_path: data/
  mask_threshold:
    1: 0.55
    2: 0.75
    3: 0.6
  min_score:
    1: 0.55
    2: 0.75
    3: 0.5

model:
  exp_name: 4X_sgd_1e-3_gauss-noise
  save_path: experiments

training:
  epochs: 100
  save_step: 10
  num_saves: 10
  shuffle: true
  num_workers: 8
  batch_size: 15
  autoresume: true

test:
  epoch_checkpoint: 50
  num_workers: 0
  batch_size: 10
  shuffle: false
  num_epoch_test: 3
  crop_dim: 512

optimizer:
  type: SGD
  lr: !!float 1e-3
  weight_decay: !!float 5e-4
  momentum: 0.9
  scheduler: false
