half_precision: False
device: cuda

architecture:
  name: Mask-RCNN
  box_detections_per_img: 540

data:
  sample_submission: data/sample_submission.csv
  train_json: data/annotations_train.json
  val_json: data/annotations_val.json
  train_path: data/train
  test_path: data/test
  mask_threshold:
    1: 0.55
    2: 0.75
    3: 0.6
  min_score:
    1: 0.55
    2: 0.75
    3: 0.5

model:
  exp_name: peller
  save_path: experiments

training:
  epochs: 100
  save_step: 10
  shuffle: true
  num_workers: 12
  batch_size: 10
  autoresume: true

optimizer:
  type: SGD
  lr: !!float 5e-3
  weight_decay: !!float 5e-4
  momentum: 0.9
